coding_task:
  description: >
    Write python code to achieve this: {assignment}
  expected_output: >
    A text file that includes the code itself, along with the output of the code. Also write the DockerFile you used to execute the code to be appended at the last
  agent: coder
  output_file: output/code_and_output.txt